spring.application.name=proxy

camel.servlet.mapping.context-path=/*

server.port=${PORT:8000}

# for debugging only
camel.main.message-history=true
camel.main.tracing=true
camel.main.source-location-enabled=false