apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJaVTV2Y25SdFlXNDZaMmh3WDJkdk1ITkxVbWx4ZVc5bWIwOXZOMGhZYkVOYU9VdHdNM0ZsWVU5MVV6QlRUbHBzZHc9PSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVmYXVsdCIKfQ==
type: kubernetes.io/dockerconfigjson
